name: docker-multicontainers
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/react-test npm test
 
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-client ./client
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-nginx ./nginx
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-api ./api
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-worker ./worker
 
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-client
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-nginx
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-api
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-worker
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: ${{ secrets.AWS_APP_NAME }}
          environment_name: ${{ secrets.AWS_ENV_NAME }}
          existing_bucket_name: ${{ secrets.AWS_BUCKET_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
