name: docker-multicontainers
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t benjaminpearce/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true benjaminpearce/react-test npm test
 
      - run: docker build -t benjaminpearce/multi-client-10-14 ./client
      - run: docker build -t benjaminpearce/multi-nginx-10-14 ./nginx
      - run: docker build -t benjaminpearce/multi-server-10-14 ./server
      - run: docker build -t benjaminpearce/multi-worker-10-14 ./worker
 
      - run: docker push benjaminpearce/multi-client-10-14
      - run: docker push benjaminpearce/multi-nginx-10-14
      - run: docker push benjaminpearce/multi-server-10-14
      - run: docker push benjaminpearce/multi-worker-10-14
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'