name: docker-multicontainers
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/react-test npm test
 
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-client ./client
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-nginx ./nginx
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-api ./api
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-worker ./worker
 
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-client
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-nginx
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-api
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-worker
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'